#!mainFile "../main.opy"

#Only remove the following directive if the gamemode does not use tricks such as A+0, A*0, "am" == "**", etc which would otherwise be optimized out.
#!optimizeStrict
#!useVariableForCompressionAlphabet


#!include "dorado.opy"
#!include "eichenwalde.opy"
#!include "gibraltar.opy"
#!include "havana.opy"
#!include "rialto.opy"
#!include "route66.opy"
#!include "shambali.opy"
#!include "circuit_royal.opy"
