macro HERO_SETTINGS_TEAM2 = {
    "general": {
        "abilityCooldown%": TEAM2_ABILITY_COOLDOWN_PCT
    }
}

macro HERO_SETTINGS_TEAM1 = {
    "bastion": {
        "secondaryFireCooldown%": BOSS_BASTION_SEC_FIRE_COOLDOWN_PCT,
        "secondaryFireKb%": BOSS_BASTION_SEC_FIRE_KB_PCT,
        "projectileSpeed%": BOSS_BASTION_PROJECTILE_SPEED_PCT,
        "enableInfiniteAmmo": BOSS_BASTION_INFINITE_AMMO,
        "health%": BOSS_BASTION_HEALTH_PCT
    },
    "wreckingBall": {
        "health%": 150,
        "ultDuration%": TEAM1_WRECKINGBALL_ULT_DURATION_PCT,
        "ultKb%": BOSS_BASTION_SEC_FIRE_KB_PCT,
        "damageReceived%": TEAM1_WRECKINGBALL_DAMAGE_RECEIVED_PCT
    },
    "general": {
        "damageReceived%": TEAM1_DAMAGE_RECEIVED_PCT,
        "abilityCooldown%": TEAM1_ABILITY_COOLDOWN_PCT,
        "health%": TEAM1_HEALTH_PCT
    }
}
