globalvar mapTitlePlayersByKey 43
globalvar titleText 44
globalvar titleColor
globalvar titlePlayer 45
globalvar playerTitleSetIndex 46
globalvar playerTitleRelation 47
globalvar rgbList 48
globalvar __currentPioneerText___ 106
globalvar __currentMapPioneerText___ 107

playervar playerTitleAndColor 37
playervar titleTextID 38
playervar rgb_vect 39
playervar info_pvar 40
playervar rgb_activated 41
playervar playerTitles 43
playervar playerTitleIndex 44
playervar playerTitleRelationIndex 45
playervar tempUnlockId
playervar earnedAchievements
