#!include "env/env_dev.opy"
#!include "locales/zh-CN.opy"
#!define ENTRY_SPECTATOR_SLOTS LOBBY_SPECTATOR_SLOTS_DEV
#!define ENTRY_ALLOW_PLAYERS_IN_QUEUE true
#!define ENTRY_AUTOREBOOT_HOURS SETTING_AUTOREBOOT_HOURS
#!define ENTRY_CLASSIC_MAP_VARIANT CLASSIC_MAP_VARIANT_OFF
#!define ENTRY_DIFFICULTY SETTING_DIFFICULTY_DEFAULT
#!include "composition/bootstrap.opy"
#!include "env/game.opy"
#!include "composition/profile-cn.opy"
#!include "env/vars_dev_extra.opy"
#!include "config/eventConfigDev.opy"
#!include "core.opy"
#!include "composition/profile-cn-features.opy"
