#!include "env/env.opy"
#!include "locales/zh-CN.opy"
#!define ENTRY_SPECTATOR_SLOTS LOBBY_SPECTATOR_SLOTS_MAIN
#!define ENTRY_ALLOW_PLAYERS_IN_QUEUE false
#!define ENTRY_AUTOREBOOT_HOURS 2
#!define ENTRY_CLASSIC_MAP_VARIANT CLASSIC_MAP_VARIANT_OFF
#!define ENTRY_DIFFICULTY 4
#!include "composition/bootstrap.opy"
#!include "../env/game.opy"
#!include "../composition/profile-cn.opy"
#!include "../config/eventConfig.opy"
#!include "../core.opy"
#!include "../composition/profile-cn-features.opy"
